# Generated by Django 3.1.3 on 2021-02-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prime_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
