# Generated by Django 3.1.3 on 2021-02-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='memo',
            name='doctype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
