name: pr

on:
  push:
    branches:
      - dev

jobs:
  masterPromotion:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Reset master branch
      run: |
          git fetch origin dev:dev
          git reset --hard dev
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: master-promotion
